### PR TITLE
Fixing keyboard covers input

### LINKED ISSUE #53: Keyboard covers input on Create User Screen
The keyboard covers the bottom input field in the `CreateUser` component. This can be fixed using a `ScrollView` and a `View` with some padding (lol), or a "`KeyboardAvoiding`" component (I've tried to make those types of components work but without luck)

### PR DESCRIPTION
**Pull request by Castau**
### ScrollView and KeyboardAvoidingView implemented in all Screens with user input
Fixes #53 
#### Examples:
**IOS**
image
_(Keyboard does not show on screenprint, put it covers all below the red line)_

**Android**
image

### UserScreen
**Android**
image

**IOS**
image

### CODE REVIEW

File: FindYourFriends/components/Card.js [hunk 1]
```diff
@@ -16,9 +16,9 @@ const styles = StyleSheet.create({
         shadowOpacity: 0.26,
         backgroundColor: 'white',
         elevation: 8,
-        padding: 20,
+        padding: 10,
         borderRadius: 10,
-        marginTop: 40
+        marginTop: 25
```
Comment (Castau) [inline FindYourFriends/components/Card.js:21]: Small change to make it look nicer with the header

File: FindYourFriends/components/Header.js [hunk 2]
```diff
@@ -13,16 +13,15 @@ const Header = props => {
...
         backgroundColor: colors.primary,
         alignItems: 'center',
         justifyContent: 'center',
-        marginTop: 30
+        marginTop: 25
     },
     headerTitle: {
         color: colors.secondary,
-        fontSize: 22,
+        fontSize: 26,
```
Comment (Castau) [inline FindYourFriends/components/Header.js:24]: small changes to header to make it slightly smaller and the text slightly bigger

**Review by MalteMagnussen — APPROVED** [review]

**Review by Runi-VN — APPROVED** [review]

**Review by MrHardcode — APPROVED** [review]
