### PR TITLE
Error Handling Frontend

### LINKED ISSUE #32: Fix Trying to save stuff in Secure Storage when login fails
image

### PR DESCRIPTION
**Pull request by MalteMagnussen**
- [x] Make an Alert. 
- [x] Handle Login Errors
- [x] Handle GraphQL Errors
- [x] Test

**How to test**
1. Open ngrok, replace the 3 places, run backend and frontend, yada yada
2. Provoke an error **(how, though? Need help - More cases)**
    1. Wrong login
    2. Make a bad request to backend somehow
3. See the Alert box with error inside. 
4. Alert box should go away when OK is pressed. 
5. Provoke a different error. 
6. See alert box with new error inside.
7. Alert box should go away when OK is pressed. 

~~Needs more testing, before I can mark it as Ready for Review, but I'd still like your thoughts.~~ 

~~This hopefully fixes this error:~~ - It is fixed on my phone. 
image

_error handling joke_
image

### CODE REVIEW

File: FindYourFriends/screens/LoginScreen.js [hunk 1]
```diff
@@ -41,11 +47,17 @@ const LoginScreen = ({ signedIn, setSignedIn, setTest, backendURL }) => {
...
         console.log("user", user);
         setSignedIn(true);
-      } else {
+      } else if (result.type == "cancel") {
+        // If the user closed the web browser, the Promise resolves with { type: 'cancel' }.
+        // If the user does not permit the application to authenticate with the given url, the Promise resolved with { type: 'cancel' }.
         console.log("User Cancelled.");
+      } else if (result.type == "dismiss") {
+        // If the browser is closed using dismissBrowser, the Promise resolves with { type: 'dismiss' }.
+        console.log("User used dismiss.");
```
Comment (MalteMagnussen) [inline FindYourFriends/screens/LoginScreen.js]:
```suggestion
        console.log("User dismissed the browser.");
```

File: FindYourFriends/screens/LoginScreen.js [hunk 2]
```diff
@@ -61,12 +73,27 @@ const LoginScreen = ({ signedIn, setSignedIn, setTest, backendURL }) => {
...
+    if (
+      res.userEmail &&
+      res.token &&
+      (typeof res.token === String || res.token instanceof String)
+    ) {
+      user.email = res.useremail;
+      user.token = res.token;
+      await SecureStore.setItemAsync(secureStoreKey, res.token);
+      setUser(user);
+      console.log(res);
```
Comment (MalteMagnussen) [inline FindYourFriends/screens/LoginScreen.js]:
```suggestion
      console.log(JSON.stringify({ res }, null, 4));
```

**Review by Castau — APPROVED** [review]
